# Generated by Django 5.0.1 on 2026-02-26 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assignment_name", models.CharField(max_length=225)),
                (
                    "assignment_deadline",
                    models.DateTimeField(
                        blank=True, help_text="Deadline for submission", null=True
                    ),
                ),
                ("file", models.FileField(upload_to="submissions/%y/%m/%d")),
                ("original_filename", models.CharField(max_length=225)),
                ("file_size", models.IntegerField(help_text="file size in bytes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("extension_requested", models.BooleanField(default=False)),
                ("extension_granted", models.BooleanField(default=False)),
                ("extension_reason", models.TextField(blank=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="classes.class",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-submitted_at"],
                        name="submissions_user_id_4507c3_idx",
                    ),
                    models.Index(
                        fields=["status"], name="submissions_status_dcc854_idx"
                    ),
                    models.Index(
                        fields=["assignment_deadline"],
                        name="submissions_assignm_6e0407_idx",
                    ),
                ],
            },
        ),
    ]
