# Generated by Django 5.0.1 on 2026-03-12 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_paused",
            field=models.BooleanField(
                default=False, help_text="Teacher paused this submission"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="paused_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paused_submission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="processed_paragraphs",
            field=models.IntegerField(
                default=0, help_text="Paragraphs analyzed so far"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="total_paragraphs",
            field=models.IntegerField(
                default=0, help_text="Total paragraphs extracted from PDF"
            ),
        ),
    ]
