# Generated by Django 5.0.1 on 2026-03-30 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_assignment"),
        ("submissions", "0002_submission_is_paused_submission_paused_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="submission",
            name="submissions_assignm_6e0407_idx",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="assignment_deadline",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="class_obj",
        ),
        migrations.AddField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Assignment this submission belongs to (null for guest uploads)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="classes.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment_name",
            field=models.CharField(
                help_text="Assignment name for guest submissions", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(upload_to="submissions/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file_size",
            field=models.IntegerField(help_text="File size in bytes"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="original_filename",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="submission",
            name="paused_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paused_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["assignment"], name="submissions_assignm_9eeb28_idx"
            ),
        ),
    ]
