# Generated by Django 5.2 on 2026-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_submission_submissions_assignm_6e0407_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
