# Generated by Django 5.2 on 2026-05-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
