# Generated by Django 5.2 on 2026-05-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_assignment_max_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='max_score',
        ),
    ]
