# Generated by GitHub Copilot on 2026-04-30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('guest', 'guest')], default='guest', help_text='User role: teacher, student, or guest', max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=4)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField()),
                ('otp_is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_user_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pendinguserregistration',
            index=models.Index(fields=['email'], name='pending_user_registr_email_12345_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinguserregistration',
            index=models.Index(fields=['otp_expires_at'], name='pending_user_registr_otp_expi_12345_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinguserregistration',
            index=models.Index(fields=['otp_is_used'], name='pending_user_registr_otp_is_u_12345_idx'),
        ),
    ]
