# Generated by Django 5.0.1 on 2026-04-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_add_otpverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameIndex(
            model_name="otpverification",
            new_name="otp_verific_user_id_5c992a_idx",
            old_name="otp_verific_user_cod_3c0a2b_idx",
        ),
        migrations.RenameIndex(
            model_name="otpverification",
            new_name="otp_verific_expires_e91cd1_idx",
            old_name="otp_verific_expires_at_8b1c3d_idx",
        ),
        migrations.RenameIndex(
            model_name="otpverification",
            new_name="otp_verific_is_used_06f132_idx",
            old_name="otp_verific_is_used_2b7e6f_idx",
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="code",
            field=models.CharField(max_length=4),
        ),
    ]
