# Generated by Django 5.0.1 on 2026-04-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_otp_and_more"),
        ("authentication", "0004_pending_user_registration"),
    ]

    operations = []
