# Generated by Django 5.0.1 on 2026-04-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_merge_20260430_0829"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pendinguserregistration",
            new_name="pending_use_email_00dee8_idx",
            old_name="pending_user_registr_email_12345_idx",
        ),
        migrations.RenameIndex(
            model_name="pendinguserregistration",
            new_name="pending_use_otp_exp_24c794_idx",
            old_name="pending_user_registr_otp_expi_12345_idx",
        ),
        migrations.RenameIndex(
            model_name="pendinguserregistration",
            new_name="pending_use_otp_is__b8adf0_idx",
            old_name="pending_user_registr_otp_is_u_12345_idx",
        ),
    ]
